server:
  port: 7779
  servlet:
    session:
      cookie:
        name: baseSessionId


spring: # Multiple environment switching
  profiles:
    active: local
  jackson: # Solve the problem of time zone difference 8, solve the problem of date object mapping string, later change to timestamp type
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+10
  mvc:
    format: # To solve the problem of date object mapping string, later change to timestamp type
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss
  cache:
    redis:
      time-to-live: 2H                          #  The cache time, 2 hours, should be longer for the production environment
    type: redis

#The log configuration
logging:
  level:
    org.springframework.web: info
    com.jolin: info
---
spring:
  servlet:
    multipart: # Upload File Configuration
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

base:
  sys:
    file-storage:
      root-path: "/file-upload/"  # The properties must be set to provide simple file upload function, file upload root path
  security:
    access:
      isWhiteLogic: true
    jwt:
      jwkSetUri: http://192.168.99.77:9998/.well-known/jwks.json  #The properties must be set to provide simple file upload function, file upload root path
      secret: mySecret      #The default value; MySecret. The signature secret key must be kept secret, must be kept secret, must be kept secret, and the production environment must be protected from other personnel
      expiration: 120  #The default value; 60. token expiration time (unit: second)
      refresh: 72000  #The default value; 1800. Automatic token refresh time (unit: second)
    login:
      retry-time: 5    # The default value; 5. Maximum number of login errors allowed in the locked-recover-second time range
      locked-recover-second: 36000 # The default value; 43200. Specifies the recovery time after login errors exceed the maximum number of times
      qrcode:
        expiration: 120  #Qr code expiration time of the QR code during the login process, in seconds. The default value; 120 seconds
    password:
      enableSM4: false # Whether to enable the sm4 encrypted transmission password. It is disabled by default
      SM4SecretKey: SM4SecretKey0000 # sm4 key. The value is a customized string. The value can contain only 16 characters
    captcha-enable: 'off'            #The default value; On. Verification code switch off On
    captcha-max-wait-second: 600  #The default value; 600. Validity period of the verification code, in seconds, 10 minutes
    captcha-same-ip-limit-per-minutes: 60 # The default value; 60. Maximum number of times a verification code is requested from the same ip address per minute
    phone-code-enable: 'off'            #The default value; On. Mobile phone verification code Login verification switch off On
    phone-code-max-wait-second: 300  #The default value; 300. Validity period, unit: seconds, 5 minutes
    phone-code-same-limit-per-minutes: 1 #The default value; 1. Limit the number of SMS messages sent per minute for the same mobile phone address
  log:
    lock: 'on'  # The default value; On. Service log switch: off Disables the service log, and on enables the service log
---
spring:
  mail:
    # Email host
    host: smtp.qq.com
    # Username
    username: 125536039@qq.com
    # Password
    password: wvhmnunivzpnbicj